In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a[-1]

np.int64(4)

In [5]:
b = np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
c = b.copy()
c


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
d = b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b[6] = 12
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
d

array([ 1,  2,  3,  4,  5,  6, 12,  8,  9])

In [11]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
c = np.array([13,14,15])
d =np.concatenate((a,c))
d
e =np.array_split(d,2)
e

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15])]

In [21]:
np.where(b==4)


(array([1]), array([0]))

In [22]:
np.where(a%2 == 0)

(array([ 1,  3,  5,  7,  9, 11]),)

In [23]:
c = np.array([3,4,2,10,5])
np.sort(c)

array([ 2,  3,  4,  5, 10])

In [24]:
c = np.array(['apple','banana','mango'])
np.sort(c)

array(['apple', 'banana', 'mango'], dtype='<U6')

In [25]:
np.random.randint(100)

56

In [26]:
np.random.rand(10)

array([0.94134206, 0.67707915, 0.7309587 , 0.51565151, 0.73188075,
       0.02712497, 0.26395733, 0.17598988, 0.92047276, 0.79666167])

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.ones(2)

array([1., 1.])